### ISSUE TITLE
Invoke-HotAdd -EnableCpu - syntax error

### ISSUE THREAD

**Issue by RBCitrix** [TheTaylorLee/PSPortableLight#1]
If you do NOT answer 'yes' to $prompt drops down to orphaned 'Else' statement (line 177) where parser thinks 'Else' is not a function

Typo line 115 'WWrite-Host'

**Comment by TheTaylorLee** [comment]
Else statement at line 160 should have been nested inside the if statement that starts at line 147. That mistake created the orphaned else statement. Now that orphaned else statement and the incorrectly located else statement will both behave correctly. The typoed Write-Host has been corrected as well.

Thank you for your input. Please post any issues for the AdminToolbox Modules in the AdminToolbox Github in the future. This will make it easier for me to reference those issues.

**Comment by TheTaylorLee** [comment]
PSPortableLight version 1.16.0 and AdminToolbox.VmwareAutomate module version 4.5.1.0 will contain the fixes.
